name: Windows Build

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-32bit:
    runs-on: self-hosted
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build 32-bit
      shell: cmd
      run: |
        echo Building 32-bit...
        call script\initenv.bat
        call script\build32.bat

  build-64bit:
    runs-on: self-hosted
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build 64-bit
      shell: cmd
      run: |
        echo Building 64-bit...
        call script\initenv.bat
        call script\build64.bat

  upload-artifacts:
    runs-on: self-hosted
    needs: [build-32bit, build-64bit]
    if: always() && (needs.build-32bit.result == 'success' || needs.build-64bit.result == 'success')
    
    steps:
    - name: Upload OpenSpeedy artifacts
      uses: actions/upload-artifact@v4
      if: needs.build-64bit.result == 'success'
      with:
        name: OpenSpeedy-artifacts
        path: |
          build/CMAKE-64bit-Release/**/OpenSpeedy.exe
          build/CMAKE-32bit-Release/**/speedpatch32.dll
          build/CMAKE-32bit-Release/**/bridge32.exe
          build/CMAKE-64bit-Release/**/speedpatch64.dll
          build/CMAKE-64bit-Release/**/bridge64.exe
        if-no-files-found: warn