name: Package
on:
  workflow_dispatch:
    inputs:
      build_id:
        description: '构建工作流ID'
        required: true
        type: string
      version:
        description: '版本号'
        required: true
        default: '1.0.0'
        type: string
      artifact_name:
        description: '签名的制品名称'
        required: true
        default: 'OpenSpeedy-unsigned-artifacts'
        type: string

jobs:
  sign:
    runs-on: windows-latest  # GitHub-hosted runner
    
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.event.inputs.artifact_name }}
        run-id: ${{ github.event.inputs.build_id }}
        path: artifacts/
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - id: upload-unsigned-artifacts
      name: Re-upload as new artifact
      uses: actions/upload-artifact@v4
      with:
        name: OpenSpeedy-unsigned-artifacts  
        path: artifacts/          
        retention-days: 30       
        
    - name: SignPath signing
      uses: signpath/github-action-submit-signing-request@v1.1
      with:
        api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
        organization-id: '58b9835d-38ea-4898-a564-76610c01cecd'
        project-slug: OpenSpeedy
        signing-policy-slug: test-signing
        github-artifact-id: ${{ steps.upload-unsigned-artifacts.outputs.artifact-id }}
        wait-for-completion: true
        output-artifact-directory: signed-artifacts/
        parameters: |
          version: ${{ toJSON(github.event.inputs.version) }}
        
    - name: Upload signed artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenSpeedy-signed-artifacts
        path: signed-artifacts/
        retention-days: 30

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Install QtInstallFramework
      run: |
        pip install aqtinstall
        python3 -m aqt install-tool -O ${{ github.workspace }}/Qt/ windows desktop tools_ifw --version 4.7.0
        echo "${{ github.workspace }}/Qt/Tools/QtInstallerFramework/4.7/bin/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - name: Package installer
      run: |
        Copy-Item -Path "signed-artifacts/*" -Destination "installer/packages/data/" -Recurse -Force
        binarycreator.exe -c %~dp0config\config.xml -p packages OpenSpeedy-${{ github.event.inputs.version }}-installer.exe


    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: OpenSpeedy-installer
        path: OpenSpeedy-${{ github.event.inputs.version }}-installer.exe
        