name: Sign
on:
  workflow_dispatch:
    inputs:
      build_id:
        description: '构建工作流ID'
        required: true
        type: string
      version:
        description: '版本号'
        required: true
        default: 'v1.0.0'
        type: string
      artifact_name:
        description: '签名的制品名称'
        required: true
        default: 'OpenSpeedy-unsigned-artifacts'
        type: string

jobs:
  sign:
    runs-on: windows-latest  # GitHub-hosted runner
    
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.event.inputs.artifact_name }}
        run-id: ${{ github.event.inputs.build_id }}
        path: artifacts/
        github-token: ${{ secrets._GITHUB_TOKEN }}

    - id: upload-unsigned-artifacts
      name: Re-upload as new artifact
      uses: actions/upload-artifact@v4
      with:
        name: OpenSpeedy-unsigned-artifacts  
        path: artifacts/          
        retention-days: 30       
        
    - name: SignPath signing
      uses: signpath/github-action-submit-signing-request@v1.1
      with:
        api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
        organization-id: '58b9835d-38ea-4898-a564-76610c01cecd'
        project-slug: OpenSpeedy
        signing-policy-slug: test-signing
        github-artifact-id: ${{ steps.upload-unsigned-artifacts.outputs.artifact-id }}
        wait-for-completion: true
        output-artifact-directory: signed-artifacts/
        parameters: |
          version: ${{ github.event.inputs.version }}
        
    - name: Upload signed artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenSpeedy-signed-artifacts
        path: signed-artifacts/
        retention-days: 30
